Options:
  Inventory:
    size: 54
    borderSlots: [0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 26, 27, 35, 36, 44, 45, 46, 47, 48, 50, 51, 52, 53]
    name: "Mob Coins Shop"
  ItemToken:
    material: DOUBLE_PLANT
    name: "&b&lMob Coin &7(Right Click!)"
    lore:
      - '&7&oMobcoins can be used in the shop to'
      - '&7&obuy limited items'
      - ''
      - '&7&o(Right Click to redeem)'
  Sound:
    inventoryOpen:
      name: BAT_TAKEOFF
      volume: 1.0
      pitch: 0.5
    addCoins:
      name: FIREWORK_TWINKLE
      volume: 1.0
      pitch: 1.5
    withdrawCoins:
      name: FIREWORK_BLAST
      volume: 1.0
      pitch: 1.5
    successfulPurchase:
      name: LEVEL_UP
      volume: 1.0
      pitch: 1.5
  Border:
    material: STAINED_GLASS_PANE
    damage: 15
    name: ' '
    amount: 1
  Balance:
    slot: 4
    material: DOUBLE_PLANT
    name: '&b&lBALANCE'
    lore:
      - ''
      - '&b&lInformation'
      - '&7Mob Coins can be used in the Transfer Menu'
      - '&7to purchase epic perks, ranks, and more.'
      - ''
      - '&b&lYour Mob Coins'
      - '&8× &7Balance &b%s'
  Info:
    slot: 49
    material: EMPTY_MAP
    name: '&b&lINFO'
    lore:
      - ''
      - '&7Mob Coins are earned by killing hostile'
      - '&7mobs, with certain mobs having higher'
      - '&7chances to drop Mob Coins.'
      - ''
      - '&b&lMob Coin Chances:'
      - '&8× &7Skeletons &b5%'
      - '&8× &7Zombies &b5%'
      - '&8× &7Blazes &b5%'
      - ''
      - '&8× &7Creepers &b8%'
      - '&8× &7Endermen &b8%'
      - ''
      - '&8× &7IronGolem &b50%'
  Shop:
    Cobblestone:
      slot: 20
      price: 25
      friendlyName: "Cobblestone"
      commands:
        - 'give %player% cobblestone'
      Item:
        material: COBBLESTONE
        name: '&d&lCobblestone'
        amount: 64
        lore:
          - ""
          - "&7Purchase this item from the Mob Coin Shop"
          - ""
          - "&8× &7Price: &b%price%"
          - ""
  Mobs:
    SKELETON: 5
    ZOMBIE: 5
    BLAZE: 5
    CREEPER: 8
    ENDERMAN: 8
    IRON_GOLEM: 50