name: MobCoins
version: 1.0.1
author: Illuzionz
main: fun.pearce.mobcoins.MobCoins

commands:
  mobcoins:
    description: The main command
    usage: /<command> <args>
    aliases: [mc, mobcoin]

permissions:
  mobcoins.openmenu:
    description: Allows the user to open the MobCoin shop
    default: op
  mobcoins.checkbal:
    description: Check your mobcoin balance
    default: op
  mobcoins.withdrawcoins:
    description: Withdraw coins from your balance
    default: op
  mobcoins.admin:
    description: The admin perm for all admin commands
    default: op
    children:
      mobcoins.givecoins:
        description: Give coins to a player
      mobcoins.removecoins:
        description: Remove coins from a player
      mobcoins.setcoins:
        description: Set a players mobcoins